# Configuration for flavours
# https://github.com/Misterio77/flavours
#
# This file should contain a [[items]] section for each application you want themed
# You can also set a shell (outside items) on which to run hooks
# Check flavours repository for more information and examples


# Explanation and default values for keys:

# # Through which shell command hooks will run. The command will be replaced in '{}'
# shell = "sh -c '{}'"
#
# [[items]]
# # File to inject to, supports tilde and env var expansion. required
# file = "~/.config/example"
# # Template to use. required
# template = "example"
#
# # Subtemplate to use
# subtemplate = "default"
# # If not rewriting, on which line (usually a comment) to start replacing
# start = "# Start flavours"
# # If not rewriting, on which line (usually a comment) to stop replacing
# end = "# End flavours"
# # Should we rewrite the entire file, instead of using the above delimiters?
# rewrite = false
# # Command to execute after injecting (goes through shell)
# hook = ""
# # Whether this hook should be executed when flavours is ran with lightweight flag
# light = true

# Example file. For sway, waybar and (beautiful)discord. Runs hooks through bash:

shell = "bash -c '{}'"

[[item]]
file = "~/.config/nvim/lua/base16.lua"
template = "nvim"
rewrite = false
start= "-- Start flavours"
end= "-- End flavours"
hook = "reloadnvim"

[[item]]
file = "~/.config/foot/colors.ini"
template = "foot"
rewrite = true

#
# [[items]]
# file = "~/.config/sway/config"
# template = "sway"
# subtemplate = "colors"
# hook = "swaymsg reload"
# light = false
#
[[items]]
file = "~/.config/waybar/style.css"
template = "waybar"
rewrite = false
start= "/* Start flavours */"
end = "/* End flavours */"

[[items]]
# generic
file = "~/.local/share/colors"
template = "generic"
rewrite = true
hook = "qutebrowser :config-source"
# qutebrowser is actually handled by generic, just needs a reload

[[item]]
file = "~/.config/rofi/themes/colors.rasi"
template = "rofi"
subtemplate = "colors"
rewrite = true

[[items]]
file = "~/.config/vesktop/themes/base16.theme.css"
template = "styles"
subtemplate = "css-variables"
rewrite = false
start= "/* Start flavours */"
end = "/* End flavours */"
